### ISSUE TITLE
How to add buttom keyboard 

### ISSUE THREAD

**Issue by Blink128net** [amirho3inf/TelegramApiClient#3]
Im work

from TelegramApiClient import client
client = Client("x")
bot = client.Bot()

@client.message()
def handle(message):
    if message.text == "/start":
        message.reply("For user👤 {}/{}".format(
            message['from']['username'] or '',

            message['from']['id'], reply_markup=ReplyKeyboardMarkup(
                                keyboard=[
                                    [KeyboardButton(text="one"), KeyboardButton(text="two")]
                                ]
                            ))
client.run()

File "f.py", line 16

    client.run()

         ^

File "f.py", line 16

    client.run()

         ^

**Comment by amirho3inf** [comment]
hi 
look at this example code 


```
from TelegramApiClient import Client, ReplyKeyboardMarkup

client = Client("x")
bot = client.Bot()

@client.message()
def handle(message):
    if message.text == "/start":
        message.reply("For user👤 {}/{}".format(
            message['from']['username'] or '',
            message['from']['id'],
            reply_markup=ReplyKeyboardMarkup([
                ["test", "test2"],
                [KeyboardButton(text="share contact", request_contact=True)]
            ],
            resize_keyboard=True)

client.run()

```

**Comment by Blink128net** [comment]
sorry for that, I mean

Im work

from TelegramApiClient import client
client = Client("x")
bot = client.Bot()

@client.message()
def handle(message):
    if message.text == "/start":
        message.reply("For user👤 {}/{}".format(
            message['from']['username'] or '',

            message['from']['id'], reply_markup=ReplyKeyboardMarkup(
                                keyboard=[
                                    [KeyboardButton(text="one"),
KeyboardButton(text="two")]
                                ]
                            ))
client.run()

File "f.py", line 16

    client.run()

         ^

File "f.py", line 16

    client.run()

         ^

Thank you for help me

**Comment by Blink128net** [comment]
import TelegramApiClient
from TelegramApiClient import Client, ReplyKeyboardMarkup

client = Client("640627234:AAHroL-4S8eio7D-RpRRa89NB49h1pSEnC4")
bot = client.Bot()

@client.message()
def handle(message):
    if message.text == "/start":
        message.reply("For user👤 {}/{}".format(
            message['from']['username'] or '',

            message['from']['id'], reply_markup=ReplyKeyboardMarkup(
                                Keyboard=[KeyboardButton(text="one"),
[KeyboardButton](text="two")]

                            )))
client.run()

  File "f.py", line 14, in handle

    Keyboard=[KeyboardButton(text="one"), [KeyboardButton](text="two")]

NameError: name 'KeyboardButton' is not defined


Can you tellme?

Pada tanggal Sel, 21 Mei 2019 07.36, Cossa Notra <newuser520842@gmail.com>
menulis:

**Comment by Blink128net** [comment]
If im added ,KeyboardButton in line 2

Then the result will be like this

exception in thread Thread-4:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line
917, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line
865, in run
    self._target(*self._args, **self._kwargs)
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/TelegramApiClient/__init__.py",
line 251, in <lambda>
    self._message_handlers.append(lambda message: func(message) if
filter(message) else None)
  File "f.py", line 14, in handle
    Keyboard=[KeyboardButton(text="one"), [KeyboardButton](text="two")]
TypeError: 'list' object is not callable

Pada tanggal Sel, 21 Mei 2019 18.25, Cossa Notra <newuser520842@gmail.com>
menulis:

**Comment by amirho3inf** [comment]
hello
you have to write your keyboard as a list of lists, you are wrong, you are calling a list!

example :

```
keyboard = [
    [KeyboardButton(text="one")],
    [KeyboardButton(text="two")]
]

reply_markup = ReplyKeyboardMarkup(keyboard)
```
